--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Aboshxm2/WaitGroup
build-by-default: true
branches:
- main
projects:
  WaitGroup:
    path: ""
    model: virion
    type: library
...
